[package]
name = "nes-emulator"
version = "0.1.0"
authors = ["Max Carvajal <jcarvajal@crimson.ua.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "*"
regex = "*"
lazy_static = "*"
sdl2 = "*"
rand = "*"